### ISSUE TITLE
Migrate to shared identity management system

### ISSUE THREAD

**Issue by clansing** [MSD-LIVE/roadmap#17]
Instead of managing users via the RDM data repository, migrate to the following:

- [ ] stand up an AWS Cognito IAM system with groups for key project teams (e.g., IM3)
- [ ] create a custom sign up page for RDM that lets users select which project teams they want to join
- [ ] create user interface so admins can approve user team membership requests
- [ ] configure RDM to use oauth authentication to Cognito
- [ ] sync RDM users and communities to Cognito users and groups, respectively

**Comment by devinsm** [comment]
Done.
