### ISSUE TITLE
Simultaneous uploads limited to 3

### ISSUE THREAD

**Issue by thurber** [MSD-LIVE/roadmap#19]
I chose 12 files at once to upload as a new dataset. Ultimately, all 12 files uploaded successfully. But I wanted to report that the GUI was initially confusing, as only three files could be uploaded at once (I initially cancelled a few times thinking only 3 files were accepted). Once the first upload completes, the next file appears. If there's a way to add something like "+9 queued files" that would prevent my confusion.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/5023771/155212921-13f6f494-3d03-4548-b289-0312445a9afa.png">

**Comment by devinsm** [comment]
We have overhauled our file management system. User's can now upload a large number of files either through the web UI, or through our new CLI.
