### ISSUE TITLE
Can't navigate back to top level of data repo

### ISSUE THREAD

**Issue by rnicholas** [MSD-LIVE/roadmap#42]
Once you've drilled down into a subset of the available datasets or are viewing a single dataset, there's no obvious way to navigate back to the top level of the data repository. An easy way to address this would be to make the large "Data Repository" text in the dark blue banner a clickable link.

**Comment by zguillen** [comment]
The "Data Repository" text in the dark blue banner is now a clickable link (this change will be included in our next release)
