### ISSUE TITLE
Can't designate "creators" with multiple roles

### ISSUE THREAD

**Issue by rnicholas** [MSD-LIVE/roadmap#44]
In most projects, contributors will have multiple roles. In many cases, it may be difficult to identify a primary role for each contributor and, in any event, it would be nice to acknowledge the specific contributions as is the practice in many journals nowadays. It's already possible to tag creators with multiple affiliations. Would it also be possible to tag them with multiple roles?

**Comment by cdburley** [comment]
Issue was raised by another user and added to our roadmap.
